services:
  - type: web
    name: n8n-service
    plan: standard
    dockerfilePath: Dockerfile
    envVars:
      - key: WEBHOOK_URL
        fromDatabase: false
        value: https://$(AUTO_NGROK_DOMAIN)/
      - key: AUTO_NGROK_DOMAIN
        value: "" # injected at runtime by ngrok startup
    startCommand: |
      ngrok authtoken $NGROK_TOKEN &&
      ngrok http 5678 --log=stdout > ngrok.log &
      n8n
databases:
  - name: n8n-db
    plan: basic-256mb

