envVarGroups:
  - name: n8n-secrets

previews:
  generation: automatic

services:
  - type: web
    name: n8n-service
    runtime: docker
    plan: standard
    dockerfilePath: Dockerfile

    envVars:
      - key: WEBHOOK_URL
        value: https://<your-app>.onrender.com/
        previewValue: https://app-pr-${RENDER_PR_NUMBER}.onrender.com/
      - key: API_ENDPOINT
        value: https://<your-app>.onrender.com/
        previewValue: https://app-pr-${RENDER_PR_NUMBER}.onrender.com/
      - fromGroup: n8n-secrets

# (Optional) Omit this block if using existing 'n8n-db' service
# databases:
#   - name: n8n-db
#     plan: basic-256mb
