services:
  - type: web
    name: n8n-service
    plan: standard
    image:
      url: docker.io/n8nio/n8n:latest
    envVars:
      - key: WEBHOOK_URL
        value: https://<your-app>.onrender.com/
    dockerfilePath: Dockerfile
    buildCommand: npm install
    startCommand: n8n
databases:
  - name: n8n-db
    plan: basic-256mb
