services:
  - type: web
    name: n8n-service
    plan: standard
    dockerfilePath: Dockerfile
    envVars:
      - key: WEBHOOK_URL
        value: https://<your-app>.onrender.com/
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: NGROK_TOKEN
        sync: false
    startCommand: |
      ngrok authtoken $NGROK_TOKEN &&
      ngrok http 5678 --log=stdout & 
      n8n
databases:
  - name: n8n-db
    plan: basic-256mb
