name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
      - name: Build Docker image
        run: docker build . -t ghcr.io/${{ github.repository }}/n8n-media:latest
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push image
        run: docker push ghcr.io/${{ github.repository }}/n8n-media:latest

  deploy:
    needs: build-scan
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Trigger Render deploy
        uses: peter-evans/http@v2
        with:
          url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
